version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DB_HOST=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dbnet

  express-js:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    container_name: expressjs-server
    expose:
      - '3000'
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DB_HOST=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

# Names our volume
volumes:
  my-db: